import numpy as np
import matplotlib.pyplot as plt

def plot_experimental_data():
    #Experimental data
    dataset1 = np.genfromtxt('amplitude')
    
    #Our results master branch. This files are generated by running validation_main()
    dataset2 = np.genfromtxt('points_of_interest_master')
    
    #Our results optimization3 branch. This files are generated by running validation_main()
    dataset3 = np.genfromtxt('points_of_interest_optimization3')
    
    #Times of experimental data
    t = dataset1[100:433,0]
    t1 = [] #Cointains the times, discarding the first ones
    for tt in t:
        t1 += [tt - t[0]]
        
    #Times of our data    
    t2 = np.arange(0., 20.0, 0.1)
    
    #Amplitude of the wave of experimental data
    displacement1 = dataset1[100:433,1]
    
    #Amplitude of the wave of our data master branch
    displacement2 = []
    for d in dataset2:
        displacement2 += [d - dataset2[0]] #compute the amplitude with respect to the initial height of the fluid in the box
    
    #Amplitude of the wave of our data
    displacement3 = []
    for d in dataset3:
        displacement3 += [d - dataset3[0]] #compute the amplitude with respect to the initial height of the fluid in the box
    
    plt.figure()
    plt.plot(t1, displacement1, color='red', label='Experimental data')
    plt.plot(t2, displacement2, color='blue', label='SPH simulation, base version')
    plt.plot(t2, displacement3, color='navy', linestyle='--', label='SPH simulation, optimization3')
    plt.xlabel('Time [s]')
    plt.xlim(0, 20)
    plt.xticks(np.arange(0, 21, 2))
    plt.ylabel('Wave amplitude near the left wall [m]')
    plt.ylim(-0.3, 0.5)
    plt.title('Validation, 2407 interior particles')
    plt.legend(frameon=False, loc=1, bbox_to_anchor=(0.89,1), prop={'size': 8})
    plt.savefig('Validation.pdf')
    plt.savefig('Validation.png')
    
if __name__ == "__main__":
    plot_experimental_data()
